//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FulgurStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public long ID { get; set; }
        public string Brand_name { get; set; }
        public string Brand_image { get; set; }
        public long SubCategory_id { get; set; }
        public bool Status { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
    }
}
