//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FulgurStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class SubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategory()
        {
            this.Brands = new HashSet<Brand>();
        }
    
        public long ID { get; set; }
        public string SubCategory_name { get; set; }
        public long Category_id { get; set; }
        public bool Status { get; set; }
        public string SubCategory_image { get; set; }
        public HttpPostedFileBase image_file { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brand> Brands { get; set; }
        public virtual Category Category { get; set; }
    }
}
